Repository Omkar-Sonawane-23/Tourism, pull requests merged in 2024-05, with the labels that each got.

#119 Made Responsive Navbar
  .gitignore
  package-lock.json
  package.json
  src/components/Navbar.jsx
Labels: GSSOC24

#129 404 Not Found Page added
  src/App.jsx
  src/pages/NotFound.jsx
Labels: GSSOC24, Level 2

#134 adding about page
  index.html
  src/App.css
  src/App.jsx
  src/components/Navbar.jsx
  src/pages/About.jsx
  src/pages/Home.jsx
Labels: GSSOC24, Level 2

#153 Places_section UI updated and responsive done
  .gitignore
  Data/Detailed.json
  README.md
  package-lock.json
  package.json
  src/components/Homeque.jsx
  src/components/Navbar.jsx
Labels: GSSOC24, Level 2

#159 Added a filter in the explore section
  src/pages/Explore.jsx
  src/pages/Home.jsx
  src/pages/Places.js
Labels: GSSOC24, Level 3

#231 Issue #157 Added Multiple Images which changes in the updated UI
  Data/Data.json
  src/components/Homeque.jsx
Labels: GSSOC24

#229 Added the Responsive ness in the Whole website
  .gitignore
  Data/Detailed.json
  src/App.jsx
  src/components/DetailView.jsx
  src/components/Details.jsx
  src/components/Homeque.jsx
  src/components/Navbar.jsx
  src/pages/ContactUs.jsx
  src/pages/Explore.jsx
  src/pages/Home.jsx
  src/pages/NotFound.jsx
  src/pages/Places.js
Labels: GSSOC24

#256 Builded explore page
  package-lock.json
  package.json
  src/pages/Explore.jsx
Labels: GSSOC24, level3

#291 Added UI for Login and Register Page
  src/App.jsx
  src/assets/bg-login.jpg
  src/assets/bg-register.jpg
  src/assets/forgot-password.png
  src/assets/google.png
  src/assets/hide-password.png
  src/assets/show-password.png
  src/components/Navbar.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
  src/styles/register.css
Labels: GSSOC24, level3

#292 [feat]: backtotop button added
  src/pages/Explore.jsx
  src/pages/GoToTop.jsx
Labels: GSSOC24, level1

#299 Contact Us Page Completed
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Accordion.jsx
  src/components/Navbar.jsx
  src/pages/ContactUs.jsx
  tailwind.config.js
Labels: GSSOC24, level3

#301 added 7 more cities in data.json and detailed.json #248
  Data/Data.json
  Data/Detailed.json
Labels: GSSOC24, level1

#288 FAQ PAGE ADDED
  src/App.jsx
  src/components/Design.jsx
  src/components/Faq-ques.js
  src/components/Faq.css
  src/components/Faq.jsx
  src/components/Navbar.jsx
Labels: GSSOC24, level2

#313 Added an image redirecting users to Register Page
  public/user.png
  src/components/Navbar.jsx
Labels: GSSOC24, level1

#331 Responsive navbar done
  src/components/Navbar.jsx
Labels: GSSOC24, level2

#330 Update Explore.jsx
  src/pages/Explore.jsx
Labels: GSSOC24, level1

#325 Added Travel Tips
  Data/Detailed.json
  src/components/Details.jsx
Labels: GSSOC24, level2

#272 changes the UI of explore page, Now there is a slideshow of backgroun…
  package-lock.json
  package.json
  src/pages/Explore.jsx
Labels: GSSOC24, level2

#347 bug resolve
  src/components/Design.jsx
  src/components/Faq.css
  src/components/Faq.jsx
Labels: GSSOC24, level1

#354 #341 Added Famous Food section
  Data/Detailed.json
  src/components/Details.jsx
Labels: GSSOC24, level3

#369 FAQ Issue fixed
  src/components/Design.jsx
Labels: GSSOC24, level1

#364 #Issue 345 solved
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: GSSOC24, level1
